services:
  db:
    env_file:
      - ./.env
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${ECOM_DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${ECOM_DB_NAME}
      MYSQL_USER: ${ECOM_DB_USER}
      MYSQL_PASSWORD: ${ECOM_DB_PASSWORD}
    volumes:
      - ./mysql_data:/var/lib/mysql
    ports:
      - "${ECOM_DB_PORT}:${ECOM_DB_PORT}"

  phpmyadmin:
    env_file:
        - ./.env
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    depends_on:
      - db
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: ${ECOM_DB_ROOT_PASSWORD}
    ports:
      - "${ECOM_PHP_MY_ADMIN_PORT}:80"

volumes:
  mysql_data:
  phpmyadmin_data: